---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates(Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - etcd
    - memcached
    - messageq
    -  ntp
    - openstack
    - sql
